library(PMCMR)
write("\\documentclass{article}", "salida.tex", append=FALSE)
write("\\title{Pruebas estad'isticas}", "salida.tex", append=TRUE)
write("\\usepackage{colortbl}", "salida.tex", append=TRUE)
write("\\usepackage[table*]{xcolor}", "salida.tex", append=TRUE)
write("\\xdefinecolor{gray95}{gray}{0.65}", "salida.tex", append=TRUE)
write("\\xdefinecolor{gray25}{gray}{0.8}", "salida.tex", append=TRUE)
write("\\author{}", "salida.tex", append=TRUE)
write("\\begin{document}", "salida.tex", append=TRUE)
write("\\maketitle", "salida.tex", append=TRUE)
write("\\begin{table*}[ht!]", "salida.tex", append=TRUE)
write("\\scriptsize", "salida.tex", append=TRUE)
write("\\caption{p-values}", "salida.tex", append=TRUE)
write("\\centering", "salida.tex", append=TRUE)
write("\\begin{tabular}{", "salida.tex", append=TRUE)
cadena<-""
write("|c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c||c|}\\hline","salida.tex",append=TRUE)
write("Indicador & 1-2 & 1-3 & 1-4 & 1-5 & 2-3 & 2-4 & 2-5 & 3-4 & 3-5 & 4-5\\\\\\hline","salida.tex",append=TRUE)
